export type ChocolateLetterChocolate = "melk" | "puur" | "wit" | "vegan-puur";
export type ChocolateLetterSize = "klein" | "groot";
export type ChocolateLetterStyle = "spuit" | "vorm";
export type ChocolateLetterSource = "winkel" | "online";

export type ChocolateLetterLine = {
  id: string;
  letter: string;
  chocolate: ChocolateLetterChocolate;
  size: ChocolateLetterSize;
  style: ChocolateLetterStyle;
  quantity: number;
  logo: boolean;
  notes: string;
};

export type ChocolateLetterOrder = {
  id: string;
  year: string;
  code: string;
  customerName: string;
  customerEmail: string;
  phone: string;
  shop: string;
  pickupDate: string;
  pickupLocation: string;
  source: ChocolateLetterSource;
  sourceKey: string;
  sourceImportedAt: string;
  sourceBatch: string;
  status: "besteld" | "in-productie" | "klaar" | "opgehaald" | "geannuleerd";
  notes: string;
  lines: ChocolateLetterLine[];
  sendCustomerEmail: boolean;
  productionDone: boolean;
  productionDoneAt: string;
  productionDoneBy: string;
  pickedUp: boolean;
  pickedUpAt: string;
  bakeryEmailSentAt: string;
  bakeryEmailError: string;
  customerConfirmationSentAt: string;
  customerConfirmationError: string;
  createdAt: string;
  updatedAt: string;
};

export type SinterklaasB2BOrder = {
  id: string;
  year: string;
  season: "sint" | "kerst" | "sint-kerst";
  customerName: string;
  contactName: string;
  customerEmail: string;
  phone: string;
  deliveryDate: string;
  productionDate: string;
  department: "chocolade" | "bakkerij" | "beide";
  orderText: string;
  letterOrderText: string;
  logo: string;
  packaging: string;
  importantNotes: string;
  priceAgreement: string;
  totalExVat: string;
  deliveryMethod: string;
  deliveryAddress: string;
  invoiceInfo: string;
  source: "handmatig" | "excel";
  sourceSheet: string;
  status: "aanvraag" | "offerte" | "akkoord" | "afgewezen";
  entered: boolean;
  productionScheduled: boolean;
  logoChecked: boolean;
  packagingChecked: boolean;
  textChecked: boolean;
  textInstructions: string;
  productionDone: boolean;
  letterProductionDone: boolean;
  packed: boolean;
  delivered: boolean;
  cancelled: boolean;
  productionDoneAt: string;
  packedAt: string;
  deliveredAt: string;
  reminderEmailedAt: string;
  reminderEmailError: string;
  confirmationEmailedAt: string;
  confirmationEmailError: string;
  createdAt: string;
  updatedAt: string;
};

export type SinterklaasListResponse<T> = {
  orders: T[];
  total?: number;
  generatedAt?: string;
};
