"use client";
import { useEffect, useMemo, useState } from "react";

type SendKind="folder"|"reminder1"|"reminder2";
type Recipient={id:string;contactName:string;email:string;doNotEmail:boolean;sent:{kind:SendKind;sentAt:string}[]};
type Customer={id:string;company:string;notes:string;recipients:Recipient[];ordered?:boolean;orderedAt?:string};
type HistoryOrder={id:string;year:string;season:string;customerName:string;date:string;orderText:string;notes:string;price:string;total:string;delivery:string;sourceSheet:string};
type Campaign={year:string;subject:string;body:string;reminder1Subject:string;reminder1Body:string;reminder2Subject:string;reminder2Body:string;folderUrl:string;customers:Customer[];history:HistoryOrder[]};
const year=String(new Date().getFullYear());
const defaults:Campaign={year,subject:"Sinterklaas voor bedrijven bij Strik Patisserie",body:"Beste {{contactpersoon}},\n\nGraag delen wij onze Sinterklaasfolder voor bedrijven. In de bijlage vindt u ons assortiment.\n\nHeeft u vragen of wilt u bestellen? Reageer gerust op deze e-mail.\n\nMet vriendelijke groet,\nStrik Patisserie",reminder1Subject:"Herinnering: Sinterklaas voor bedrijven",reminder1Body:"Beste {{contactpersoon}},\n\nHeeft u onze Sinterklaasfolder al kunnen bekijken? We denken graag mee over een passende bestelling.\n\nMet vriendelijke groet,\nStrik Patisserie",reminder2Subject:"Laatste herinnering: Sinterklaas voor bedrijven",reminder2Body:"Beste {{contactpersoon}},\n\nDit is onze laatste herinnering voor het zakelijke Sinterklaasassortiment. Neem gerust contact met ons op als we iets kunnen betekenen.\n\nMet vriendelijke groet,\nStrik Patisserie",folderUrl:"",customers:[],history:[]};
async function api(method="GET",body?:unknown){const response=await fetch(`/api/sinterklaas-mailing?year=${year}`,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Mailing kon niet worden verwerkt.");return data as Partial<Campaign>&{needsImport?:boolean}}
const stamp=(r:Recipient,k:SendKind)=>r.sent.find(e=>e.kind===k)?.sentAt||"";
const date=(v:string)=>v?new Date(v).toLocaleString("nl-NL",{dateStyle:"short",timeStyle:"short"}):"–";
const forStorage=(campaign:Campaign)=>{const {history: _history,...stored}=campaign;return stored};
const companyKey=(value:string)=>value.toLowerCase().replace(/\b(t\.?a\.?v\.?|tav)\b.*$/i,"").replace(/[^a-z0-9]+/g,"");

export default function SinterklaasMailingClient(){
 const [campaign,setCampaign]=useState<Campaign>(defaults),[message,setMessage]=useState("Mailing laden..."),[saving,setSaving]=useState(false),[search,setSearch]=useState("");
 const shown=useMemo(()=>campaign.customers.filter(c=>`${c.company} ${c.notes} ${c.recipients.map(r=>`${r.contactName} ${r.email}`).join(" ")}`.toLowerCase().includes(search.toLowerCase())),[campaign.customers,search]);
 useEffect(()=>{void api().then(async data=>{const loaded={...defaults,...data,customers:Array.isArray(data.customers)?data.customers:[]};setCampaign(loaded);if(!data.needsImport){setMessage("");return}setMessage("Klantenlijst uit 2024 centraal opslaan...");const saved=await api("POST",loaded);setCampaign({...loaded,...saved} as Campaign);setMessage("141 klanten en 175 e-mailadressen uit 2024 zijn geïmporteerd.")}).catch(e=>setMessage(e.message))},[]);
 const patch=(v:Partial<Campaign>)=>setCampaign(c=>({...c,...v}));
 const patchCustomer=(id:string,v:Partial<Customer>)=>patch({customers:campaign.customers.map(c=>c.id===id?{...c,...v}:c)});
 const patchRecipient=(cid:string,rid:string,v:Partial<Recipient>)=>patch({customers:campaign.customers.map(c=>c.id===cid?{...c,recipients:c.recipients.map(r=>r.id===rid?{...r,...v}:r)}:c)});
 async function save(){setSaving(true);try{const data=await api("POST",forStorage(campaign));setCampaign({...campaign,...data} as Campaign);setMessage("Klantenlijst en mailing opgeslagen in WordPress.")}catch(e){setMessage(e instanceof Error?e.message:"Opslaan mislukt.")}finally{setSaving(false)}}
 function addCustomer(){patch({customers:[{id:`klant-${Date.now()}`,company:"",notes:"",recipients:[{id:`adres-${Date.now()}`,contactName:"",email:"",doNotEmail:false,sent:[]}]},...campaign.customers]})}
 function addRecipient(c:Customer){patchCustomer(c.id,{recipients:[...c.recipients,{id:`adres-${Date.now()}`,contactName:"",email:"",doNotEmail:false,sent:[]}]})}
 function addHistoryCustomer(order:HistoryOrder){if(campaign.customers.some(c=>companyKey(c.company)===companyKey(order.customerName))){setMessage(`${order.customerName} staat al in de mailinglijst.`);return}patch({customers:[{id:`klant-historie-${Date.now()}`,company:order.customerName,notes:`Historische ${order.season}-klant (${order.year})`,recipients:[{id:`adres-${Date.now()}`,contactName:"",email:"",doNotEmail:false,sent:[]}]},...campaign.customers]});setMessage(`${order.customerName} toegevoegd. Vul nu het e-mailadres in en sla de campagne op.`)}
 async function send(c:Customer,r:Recipient,k:SendKind){if(!r.email||r.doNotEmail)return;const label=k==="folder"?"de foldermail":k==="reminder1"?"reminder 1":"reminder 2";if(!confirm(`${label} nu versturen naar ${r.email}?`))return;setSaving(true);try{const data=await api("PATCH",{year,customerId:c.id,recipientId:r.id,kind:k,campaign:forStorage(campaign)});setCampaign({...campaign,...data} as Campaign);setMessage(`${label} verstuurd naar ${r.email}.`)}catch(e){setMessage(e instanceof Error?e.message:"Versturen mislukt.")}finally{setSaving(false)}}
 return <div className="space-y-4">
  {message&&<p className="rounded-lg border border-[#d6e5d8] bg-[#f6faf4] p-3 text-sm font-bold">{message}</p>}
  <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{[["Klanten",campaign.customers.length],["Folder verstuurd",campaign.customers.filter(c=>c.recipients.some(r=>stamp(r,"folder"))).length],["Besteld",campaign.customers.filter(c=>c.ordered).length],["Historische orders",campaign.history.length]].map(([label,value])=><div key={label} className="rounded-xl border border-[#d6e5d8] bg-white p-3"><p className="text-xs font-bold text-[#716a62]">{label}</p><p className="text-2xl font-black">{value}</p></div>)}</div>
  <section className="rounded-xl border border-[#d6e5d8] bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-xl font-black">Campagne {campaign.year}</h2><p className="text-sm text-[#716a62]">Afzender en reply-to: info@strik-patisserie.nl</p></div><button className="allergen-small-button bg-[#31552a] text-white" disabled={saving} onClick={()=>void save()}>{saving?"Bezig...":"Campagne opslaan"}</button></div><label className="block text-xs font-black">Link naar B2B-folder (PDF)<input className="allergen-input mt-1" value={campaign.folderUrl} onChange={e=>patch({folderUrl:e.target.value})} placeholder="https://strik-patisserie.nl/.../folder.pdf"/></label><div className="mt-3 grid gap-3 lg:grid-cols-3">{([['subject','body','Eerste foldermail'],['reminder1Subject','reminder1Body','Reminder 1'],['reminder2Subject','reminder2Body','Reminder 2']] as const).map(([s,b,l])=><div key={l} className="rounded-lg border border-[#e5e0d9] p-3"><h3 className="mb-2 font-black">{l}</h3><input className="allergen-input" value={campaign[s]} onChange={e=>patch({[s]:e.target.value})}/><textarea className="allergen-input mt-2 min-h-48 resize-y" value={campaign[b]} onChange={e=>patch({[b]:e.target.value})}/><p className="mt-1 text-[.68rem] text-[#777067]">Gebruik {'{{contactpersoon}}'} voor de aanhef.</p></div>)}</div></section>
  <section className="rounded-xl border border-[#d6e5d8] bg-white p-4 shadow-sm"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-xl font-black">Klanten en e-mailadressen</h2><p className="text-sm text-[#716a62]">{campaign.customers.length} klanten · {campaign.customers.reduce((n,c)=>n+c.recipients.length,0)} adressen</p></div><div className="flex gap-2"><input className="allergen-input max-w-xs" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Zoeken..."/><button className="allergen-small-button" onClick={addCustomer}>+ Klant toevoegen</button></div></div>
   <div className="space-y-3">{shown.map(c=><article key={c.id} className="rounded-lg border border-[#e5e0d9] p-3"><div className="flex flex-wrap gap-2"><input className="allergen-input min-w-64 flex-1 font-black" value={c.company} onChange={e=>patchCustomer(c.id,{company:e.target.value})} placeholder="Bedrijfsnaam"/><label className={`flex items-center gap-2 rounded-lg border px-3 text-sm font-black ${c.ordered?"border-[#6f8d65] bg-[#edf5ea]":"border-[#ddd7cf]"}`}><input type="checkbox" checked={!!c.ordered} onChange={e=>patchCustomer(c.id,{ordered:e.target.checked,orderedAt:e.target.checked?new Date().toISOString():""})}/> Besteld voor {year}</label><button className="allergen-small-button" onClick={()=>addRecipient(c)}>+ E-mailadres</button><button className="px-2 text-sm font-bold text-red-700" onClick={()=>patch({customers:campaign.customers.filter(x=>x.id!==c.id)})}>Klant verwijderen</button></div><div className="mt-2 space-y-2">{c.recipients.map(r=><div key={r.id} className="rounded-md bg-[#faf8f5] p-2"><div className="grid gap-2 md:grid-cols-[1fr_1.2fr_auto]"><input className="allergen-input" value={r.contactName} onChange={e=>patchRecipient(c.id,r.id,{contactName:e.target.value})} placeholder="Contactpersoon"/><input className="allergen-input" type="email" value={r.email} onChange={e=>patchRecipient(c.id,r.id,{email:e.target.value})} placeholder="E-mailadres"/><button className="px-2 text-sm font-bold text-red-700" onClick={()=>patchCustomer(c.id,{recipients:c.recipients.filter(x=>x.id!==r.id)})}>Adres verwijderen</button></div><div className="mt-2 flex flex-wrap items-center gap-2"><button className="allergen-small-button" disabled={saving||!!stamp(r,'folder')||r.doNotEmail} onClick={()=>void send(c,r,'folder')}>{stamp(r,'folder')?`Folder ${date(stamp(r,'folder'))}`:"Folder versturen"}</button><button className="allergen-small-button" disabled={saving||!stamp(r,'folder')||!!stamp(r,'reminder1')||r.doNotEmail} onClick={()=>void send(c,r,'reminder1')}>{stamp(r,'reminder1')?`Reminder 1 ${date(stamp(r,'reminder1'))}`:"Reminder 1"}</button><button className="allergen-small-button" disabled={saving||!stamp(r,'reminder1')||!!stamp(r,'reminder2')||r.doNotEmail} onClick={()=>void send(c,r,'reminder2')}>{stamp(r,'reminder2')?`Reminder 2 ${date(stamp(r,'reminder2'))}`:"Reminder 2"}</button><label className="ml-auto flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={r.doNotEmail} onChange={e=>patchRecipient(c.id,r.id,{doNotEmail:e.target.checked})}/> Niet meer mailen</label></div></div>)}</div><input className="allergen-input mt-2" value={c.notes} onChange={e=>patchCustomer(c.id,{notes:e.target.value})} placeholder="Notities over deze klant"/></article>)}{!shown.length&&<p className="text-sm text-[#777067]">Geen klanten gevonden.</p>}</div>
  </section>
  <section className="rounded-xl border border-[#d6e5d8] bg-white p-4 shadow-sm"><h2 className="text-xl font-black">Archief B2B-bestellingen</h2><p className="mb-3 text-sm text-[#716a62]">Sinterklaas en Kerst 2019–2025 · {campaign.history.length} bestellingen</p><div className="max-h-[42rem] overflow-auto"><table className="w-full min-w-[900px] border-collapse text-sm"><thead className="sticky top-0 bg-white"><tr className="border-b-2 border-[#c3d3bc] text-left"><th className="p-2">Jaar</th><th className="p-2">Seizoen</th><th className="p-2">Klant</th><th className="p-2">Bestelling</th><th className="p-2">Levering</th><th className="p-2">Totaal</th><th className="p-2">Mailing</th></tr></thead><tbody>{campaign.history.map(order=>{const exists=campaign.customers.some(c=>companyKey(c.company)===companyKey(order.customerName));return <tr key={order.id} className="border-b border-[#ece8e2] align-top"><td className="p-2">{order.year}</td><td className="p-2 capitalize">{order.season}</td><td className="p-2 font-bold">{order.customerName}</td><td className="max-w-md whitespace-pre-line p-2">{order.orderText}{order.notes&&<p className="mt-1 text-xs italic text-[#716a62]">{order.notes}</p>}</td><td className="p-2">{order.date} {order.delivery}</td><td className="p-2">{order.total||order.price||"–"}</td><td className="p-2"><button className="allergen-small-button" disabled={exists} onClick={()=>addHistoryCustomer(order)}>{exists?"In lijst":"Aan mailinglijst"}</button></td></tr>})}</tbody></table></div></section>
 </div>
}
