import type { Ingredient, InvoiceImport, Recipe } from "./types";

export const bakeryIcons = {
  bakkerij: "/apps%20strik_Bakkerij.svg",
  recepturen: "/apps%20strik_recepten.svg",
};

export const productGroups = [
  "Gebak",
  "Taarten",
  "Sloffen",
  "Koek",
  "IJs",
  "Bonbons",
];

export const ingredients: Ingredient[] = [
  {
    id: "slagroom-35",
    name: "Slagroom 35%",
    supplier: "Beko",
    supplierArticleNumber: "BE-10342",
    packageSize: "10 liter",
    recipeUnit: "liter",
    lastPrice: 34.8,
    previousPrice: 32,
    pricePerBaseUnit: 3.48,
    allergens: ["Melk"],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Debic Slagroom 35% 10L", "Room 35%", "Slagroom Debic"],
  },
  {
    id: "roomboter",
    name: "Roomboter",
    supplier: "Beko",
    supplierArticleNumber: "BE-22018",
    packageSize: "10 kg",
    recipeUnit: "kg",
    lastPrice: 82.5,
    previousPrice: 78.2,
    pricePerBaseUnit: 8.25,
    allergens: ["Melk"],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Boter ongezouten", "Melkerijboter"],
  },
  {
    id: "pure-chocolade",
    name: "Pure chocolade",
    supplier: "Sligro",
    supplierArticleNumber: "SL-88120",
    packageSize: "2,5 kg",
    recipeUnit: "kg",
    lastPrice: 38.75,
    previousPrice: 36.1,
    pricePerBaseUnit: 15.5,
    allergens: ["Soja"],
    lastUpdated: "2026-05-11",
    status: "active",
    lastInvoice: "Sligro 88720",
    aliases: ["Callets puur", "Donkere chocolade"],
  },
  {
    id: "witte-chocolade",
    name: "Witte chocolade",
    supplier: "Beko",
    supplierArticleNumber: "BE-88044",
    packageSize: "2,5 kg",
    recipeUnit: "kg",
    lastPrice: 35.5,
    previousPrice: 34.4,
    pricePerBaseUnit: 14.2,
    allergens: ["Melk", "Soja"],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Witte callets", "Chocolade wit"],
  },
  {
    id: "pistachepasta",
    name: "Pistachepasta",
    supplier: "Zeelandia",
    supplierArticleNumber: "ZE-44012",
    packageSize: "3 kg",
    recipeUnit: "kg",
    lastPrice: 119.7,
    previousPrice: 101.4,
    pricePerBaseUnit: 39.9,
    allergens: ["Noten"],
    lastUpdated: "2026-05-16",
    status: "active",
    lastInvoice: "Zeelandia 90031",
    aliases: ["Pistache pasta", "Pistache compound"],
  },
  {
    id: "amandelmeel",
    name: "Amandelmeel",
    supplier: "Beko",
    supplierArticleNumber: "BE-66109",
    packageSize: "5 kg",
    recipeUnit: "kg",
    lastPrice: 64.5,
    previousPrice: 61,
    pricePerBaseUnit: 12.9,
    allergens: ["Noten"],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Amandelpoeder", "Amandelen gemalen"],
  },
  {
    id: "suiker",
    name: "Suiker",
    supplier: "Beko",
    supplierArticleNumber: "BE-11002",
    packageSize: "25 kg",
    recipeUnit: "kg",
    lastPrice: 31.25,
    previousPrice: 30.5,
    pricePerBaseUnit: 1.25,
    allergens: [],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Kristalsuiker"],
  },
  {
    id: "bloem",
    name: "Bloem",
    supplier: "Beko",
    supplierArticleNumber: "BE-33110",
    packageSize: "25 kg",
    recipeUnit: "kg",
    lastPrice: 26.25,
    previousPrice: 25.75,
    pricePerBaseUnit: 1.05,
    allergens: ["Gluten"],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Tarwebloem", "Patentbloem"],
  },
  {
    id: "gelatine",
    name: "Gelatine",
    supplier: "Beko",
    supplierArticleNumber: "BE-77120",
    packageSize: "1 kg",
    recipeUnit: "gram",
    lastPrice: 28.4,
    previousPrice: 27.6,
    pricePerBaseUnit: 0.0284,
    allergens: [],
    lastUpdated: "2026-05-18",
    status: "active",
    lastInvoice: "Beko 2026-1842",
    aliases: ["Gelatineblaadjes", "Gelatine poeder"],
  },
  {
    id: "mascarpone",
    name: "Mascarpone",
    supplier: "Sligro",
    supplierArticleNumber: "SL-22041",
    packageSize: "2 kg",
    recipeUnit: "kg",
    lastPrice: 17.9,
    previousPrice: 16.8,
    pricePerBaseUnit: 8.95,
    allergens: ["Melk"],
    lastUpdated: "2026-05-14",
    status: "active",
    lastInvoice: "Sligro 88720",
    aliases: ["Mascarpone kaas"],
  },
  {
    id: "roomkaas",
    name: "Roomkaas",
    supplier: "Sligro",
    supplierArticleNumber: "SL-22102",
    packageSize: "2 kg",
    recipeUnit: "kg",
    lastPrice: 16.4,
    previousPrice: 15.45,
    pricePerBaseUnit: 8.2,
    allergens: ["Melk"],
    lastUpdated: "2026-05-14",
    status: "active",
    lastInvoice: "Sligro 88720",
    aliases: ["Cream cheese", "Philadelphia naturel"],
  },
  {
    id: "frambozenpuree",
    name: "Frambozenpuree",
    supplier: "Zeelandia",
    supplierArticleNumber: "ZE-77201",
    packageSize: "5 kg",
    recipeUnit: "kg",
    lastPrice: 49.75,
    previousPrice: 46.5,
    pricePerBaseUnit: 9.95,
    allergens: [],
    lastUpdated: "2026-05-16",
    status: "active",
    lastInvoice: "Zeelandia 90031",
    aliases: ["Puree framboos", "Framboos diepvriespuree"],
  },
];

export const recipes: Recipe[] = [
  {
    id: "biscuit",
    name: "Biscuit",
    type: "semiFinished",
    productGroup: "Basis",
    salesPrice: 0,
    costPrice: 6.8,
    previousCostPrice: 6.45,
    targetMargin: 0,
    currentMargin: 0,
    status: "active",
    ingredients: [
      { ingredientId: "bloem", quantity: 1200, unit: "gram", costContribution: 1.26 },
      { ingredientId: "suiker", quantity: 900, unit: "gram", costContribution: 1.13 },
      { ingredientId: "roomboter", quantity: 420, unit: "gram", costContribution: 3.47 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Eieren en suiker luchtig kloppen.",
      "Bloem spatelen en boter voorzichtig mengen.",
      "Bakken op 180 graden tot de biscuit veerkrachtig aanvoelt.",
    ],
    allergens: ["Gluten", "Melk", "Ei"],
    version: "v4.2",
    lastUpdated: "2026-05-12",
    portionLabel: "1 batch",
    batchSize: "3 platen",
    photoHint: "Luchtige basis voor gebak en taarten",
    notes: "Na afkoelen direct afdekken tegen uitdrogen.",
    linkedFinalProductIds: ["petit-gateau-pistache", "nougatine-taart", "red-velvet"],
  },
  {
    id: "cremeux-vanille",
    name: "Cremeux vanille",
    type: "semiFinished",
    productGroup: "Vullingen",
    salesPrice: 0,
    costPrice: 18.4,
    previousCostPrice: 17.2,
    targetMargin: 0,
    currentMargin: 0,
    status: "active",
    ingredients: [
      { ingredientId: "slagroom-35", quantity: 2.4, unit: "liter", costContribution: 8.35 },
      { ingredientId: "witte-chocolade", quantity: 560, unit: "gram", costContribution: 7.95 },
      { ingredientId: "gelatine", quantity: 42, unit: "gram", costContribution: 1.19 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Room met vanille verwarmen.",
      "Gelatine oplossen en op chocolade gieten.",
      "Emulgeren, doorkoelen en glad mixen voor gebruik.",
    ],
    allergens: ["Melk", "Soja"],
    version: "v2.6",
    lastUpdated: "2026-05-18",
    portionLabel: "1 batch",
    batchSize: "3,2 kg",
    photoHint: "Zachte vanille cremeux",
    notes: "Minimaal 8 uur laten kristalliseren.",
    linkedFinalProductIds: ["petit-gateau-pistache", "cheesecake-seizoen"],
  },
  {
    id: "pistache-mousse",
    name: "Pistache mousse",
    type: "semiFinished",
    productGroup: "Mousses",
    salesPrice: 0,
    costPrice: 31.2,
    previousCostPrice: 26.6,
    targetMargin: 0,
    currentMargin: 0,
    status: "active",
    ingredients: [
      { ingredientId: "slagroom-35", quantity: 3.1, unit: "liter", costContribution: 10.79 },
      { ingredientId: "pistachepasta", quantity: 420, unit: "gram", costContribution: 16.76 },
      { ingredientId: "gelatine", quantity: 36, unit: "gram", costContribution: 1.02 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Pistachebasis maken en afkoelen tot handwarm.",
      "Halfgeslagen room in twee delen spatelen.",
      "Direct verwerken of strak afgedekt koelen.",
    ],
    allergens: ["Melk", "Noten"],
    version: "v3.1",
    lastUpdated: "2026-05-16",
    portionLabel: "1 batch",
    batchSize: "4 kg",
    photoHint: "Groene pistachemousse voor gebak",
    notes: "Pistachepasta is grootste kostprijsdriver.",
    linkedFinalProductIds: ["petit-gateau-pistache", "pistache-slofje"],
  },
  {
    id: "spiegelglacage",
    name: "Spiegelglacage",
    type: "semiFinished",
    productGroup: "Afwerking",
    salesPrice: 0,
    costPrice: 14.7,
    previousCostPrice: 14.1,
    targetMargin: 0,
    currentMargin: 0,
    status: "active",
    ingredients: [
      { ingredientId: "witte-chocolade", quantity: 650, unit: "gram", costContribution: 9.23 },
      { ingredientId: "suiker", quantity: 900, unit: "gram", costContribution: 1.13 },
      { ingredientId: "gelatine", quantity: 52, unit: "gram", costContribution: 1.48 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Suikerstroop koken.",
      "Over chocolade en gelatine gieten.",
      "Staafmixen zonder lucht en gebruiken op 32 graden.",
    ],
    allergens: ["Melk", "Soja"],
    version: "v1.9",
    lastUpdated: "2026-05-10",
    portionLabel: "1 batch",
    batchSize: "2,8 kg",
    photoHint: "Glanzende neutrale glacage",
    notes: "Kleurstof apart registreren zodra database live is.",
    linkedFinalProductIds: ["petit-gateau-pistache", "cheesecake-seizoen"],
  },
  {
    id: "kersen-bitterkoekjes-vulling",
    name: "Kersen-bitterkoekjes vulling",
    type: "semiFinished",
    productGroup: "Vullingen",
    salesPrice: 0,
    costPrice: 22.3,
    previousCostPrice: 21.9,
    targetMargin: 0,
    currentMargin: 0,
    status: "draft",
    ingredients: [
      { ingredientId: "amandelmeel", quantity: 700, unit: "gram", costContribution: 9.03 },
      { ingredientId: "suiker", quantity: 800, unit: "gram", costContribution: 1 },
      { ingredientId: "frambozenpuree", quantity: 1.1, unit: "kg", costContribution: 10.95 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Fruitbasis inkoken tot stevig.",
      "Bitterkoekjesmassa mengen en in lagen verwerken.",
    ],
    allergens: ["Noten"],
    version: "v0.8",
    lastUpdated: "2026-05-09",
    portionLabel: "1 batch",
    batchSize: "3 kg",
    photoHint: "Seizoensvulling voor taarten",
    notes: "Nog proefsessie nodig voor definitieve verhouding.",
    linkedFinalProductIds: ["cheesecake-seizoen"],
  },
  {
    id: "brownie-bodem",
    name: "Brownie bodem",
    type: "semiFinished",
    productGroup: "Bodems",
    salesPrice: 0,
    costPrice: 16.1,
    previousCostPrice: 15.4,
    targetMargin: 0,
    currentMargin: 0,
    status: "active",
    ingredients: [
      { ingredientId: "pure-chocolade", quantity: 650, unit: "gram", costContribution: 10.08 },
      { ingredientId: "roomboter", quantity: 420, unit: "gram", costContribution: 3.47 },
      { ingredientId: "bloem", quantity: 500, unit: "gram", costContribution: 0.53 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Chocolade en boter smelten.",
      "Beslag mengen en laag uitsmeren.",
      "Kort bakken zodat de bodem smeuig blijft.",
    ],
    allergens: ["Gluten", "Melk", "Soja"],
    version: "v2.0",
    lastUpdated: "2026-05-13",
    portionLabel: "1 batch",
    batchSize: "2 platen",
    photoHint: "Stevige chocoladelaag",
    notes: "Ook inzetbaar voor dessertcups.",
    linkedFinalProductIds: ["red-velvet"],
  },
  {
    id: "slagroomvulling",
    name: "Slagroomvulling",
    type: "semiFinished",
    productGroup: "Vullingen",
    salesPrice: 0,
    costPrice: 13.6,
    previousCostPrice: 12.5,
    targetMargin: 0,
    currentMargin: 0,
    status: "active",
    ingredients: [
      { ingredientId: "slagroom-35", quantity: 3.4, unit: "liter", costContribution: 11.83 },
      { ingredientId: "suiker", quantity: 450, unit: "gram", costContribution: 0.56 },
      { ingredientId: "gelatine", quantity: 18, unit: "gram", costContribution: 0.51 },
    ],
    semiFinishedItems: [],
    preparationSteps: [
      "Room met suiker opslaan.",
      "Gelatinebasis mengen voor stevigheid.",
      "Direct verwerken op koude taartlagen.",
    ],
    allergens: ["Melk"],
    version: "v1.5",
    lastUpdated: "2026-05-18",
    portionLabel: "1 batch",
    batchSize: "3,6 kg",
    photoHint: "Basis slagroomvulling",
    notes: "Let op temperatuur bij warme dagen.",
    linkedFinalProductIds: ["nougatine-taart", "slagroomtruffels"],
  },
  {
    id: "petit-gateau-pistache",
    name: "Petit Gateau Pistache",
    type: "finalProduct",
    productGroup: "Gebak",
    salesPrice: 8.95,
    costPrice: 1.68,
    previousCostPrice: 1.41,
    targetMargin: 80,
    currentMargin: 81,
    status: "active",
    ingredients: [
      { ingredientId: "pistachepasta", quantity: 12, unit: "gram", costContribution: 0.48 },
      { ingredientId: "witte-chocolade", quantity: 8, unit: "gram", costContribution: 0.11 },
    ],
    semiFinishedItems: [
      { semiFinishedRecipeId: "biscuit", quantity: 18, unit: "gram", costContribution: 0.18 },
      { semiFinishedRecipeId: "pistache-mousse", quantity: 48, unit: "gram", costContribution: 0.38 },
      { semiFinishedRecipeId: "cremeux-vanille", quantity: 22, unit: "gram", costContribution: 0.21 },
      { semiFinishedRecipeId: "spiegelglacage", quantity: 16, unit: "gram", costContribution: 0.12 },
    ],
    preparationSteps: [
      "Biscuit uitsteken en in siliconenmat plaatsen.",
      "Pistache mousse doseren en cremeux kern invriezen.",
      "Lossen, glaceren en decoreren met pistache.",
    ],
    allergens: ["Gluten", "Melk", "Ei", "Noten", "Soja"],
    version: "v5.4",
    lastUpdated: "2026-05-18",
    portionLabel: "per stuk",
    batchSize: "30 stuks",
    photoHint: "Strakke groene petit gateau",
    notes: "Decoratie apart wegen bij feestdagen.",
    decorationCost: 0.2,
    packagingCost: 0,
  },
  {
    id: "nougatine-taart",
    name: "Nougatine taart",
    type: "finalProduct",
    productGroup: "Taarten",
    salesPrice: 47.5,
    costPrice: 11.4,
    previousCostPrice: 9.8,
    targetMargin: 80,
    currentMargin: 76,
    status: "active",
    ingredients: [
      { ingredientId: "amandelmeel", quantity: 220, unit: "gram", costContribution: 2.84 },
      { ingredientId: "roomboter", quantity: 180, unit: "gram", costContribution: 1.49 },
    ],
    semiFinishedItems: [
      { semiFinishedRecipeId: "biscuit", quantity: 550, unit: "gram", costContribution: 1.85 },
      { semiFinishedRecipeId: "slagroomvulling", quantity: 920, unit: "gram", costContribution: 3.45 },
    ],
    preparationSteps: [
      "Biscuit lagen snijden.",
      "Vullen met slagroomvulling en nougatine.",
      "Afsmeren, aanzetten met nougatine en decoreren.",
    ],
    allergens: ["Gluten", "Melk", "Ei", "Noten"],
    version: "v3.8",
    lastUpdated: "2026-05-18",
    portionLabel: "10-12 personen",
    batchSize: "1 taart",
    photoHint: "Klassieke Strik nougatine",
    notes: "Onder margegrens na roomprijsupdate.",
    decorationCost: 1.12,
    packagingCost: 0.65,
  },
  {
    id: "slagroomtruffels",
    name: "Slagroomtruffels",
    type: "finalProduct",
    productGroup: "Bonbons",
    salesPrice: 2.5,
    costPrice: 0.39,
    previousCostPrice: 0.38,
    targetMargin: 80,
    currentMargin: 86,
    status: "active",
    ingredients: [
      { ingredientId: "pure-chocolade", quantity: 16, unit: "gram", costContribution: 0.25 },
    ],
    semiFinishedItems: [
      { semiFinishedRecipeId: "slagroomvulling", quantity: 24, unit: "gram", costContribution: 0.09 },
    ],
    preparationSteps: [
      "Slagroomvulling opspuiten en invriezen.",
      "Doorhalen in pure chocolade.",
      "Afwerken met cacao en koud bewaren.",
    ],
    allergens: ["Melk", "Soja"],
    version: "v2.7",
    lastUpdated: "2026-05-08",
    portionLabel: "per stuk",
    batchSize: "120 stuks",
    photoHint: "Ambachtelijke slagroomtruffel",
    notes: "Stabiele marge, wel gevoelig voor chocoladeprijs.",
    decorationCost: 0.03,
    packagingCost: 0.02,
  },
  {
    id: "red-velvet",
    name: "Red Velvet",
    type: "finalProduct",
    productGroup: "Taarten",
    salesPrice: 59.5,
    costPrice: 12.4,
    previousCostPrice: 12.1,
    targetMargin: 80,
    currentMargin: 79,
    status: "active",
    ingredients: [
      { ingredientId: "roomkaas", quantity: 720, unit: "gram", costContribution: 5.9 },
      { ingredientId: "suiker", quantity: 450, unit: "gram", costContribution: 0.56 },
    ],
    semiFinishedItems: [
      { semiFinishedRecipeId: "biscuit", quantity: 620, unit: "gram", costContribution: 2.1 },
      { semiFinishedRecipeId: "brownie-bodem", quantity: 260, unit: "gram", costContribution: 1.18 },
    ],
    preparationSteps: [
      "Bodem plaatsen en red velvet lagen opbouwen.",
      "Roomkaascreme verdelen.",
      "Strak afwerken en koud laten opstijven.",
    ],
    allergens: ["Gluten", "Melk", "Ei", "Soja"],
    version: "v4.0",
    lastUpdated: "2026-05-14",
    portionLabel: "12 personen",
    batchSize: "1 taart",
    photoHint: "Rode taart met roomkaascreme",
    notes: "Prijs net onder doelmarge door roomkaas.",
    decorationCost: 1.2,
    packagingCost: 0.75,
  },
  {
    id: "pistache-slofje",
    name: "Pistache slofje",
    type: "finalProduct",
    productGroup: "Sloffen",
    salesPrice: 7.95,
    costPrice: 2.34,
    previousCostPrice: 1.92,
    targetMargin: 80,
    currentMargin: 71,
    status: "active",
    ingredients: [
      { ingredientId: "pistachepasta", quantity: 28, unit: "gram", costContribution: 1.12 },
      { ingredientId: "amandelmeel", quantity: 38, unit: "gram", costContribution: 0.49 },
    ],
    semiFinishedItems: [
      { semiFinishedRecipeId: "pistache-mousse", quantity: 42, unit: "gram", costContribution: 0.33 },
    ],
    preparationSteps: [
      "Sloffenbodem bakken.",
      "Pistachevulling opspuiten.",
      "Afwerken met pistache, creme en klein decor.",
    ],
    allergens: ["Gluten", "Melk", "Ei", "Noten"],
    version: "v1.6",
    lastUpdated: "2026-05-16",
    portionLabel: "per stuk",
    batchSize: "24 stuks",
    photoHint: "Pistache slof met luxe afwerking",
    notes: "Advies: verkoopprijs herzien of pistache-inzet verlagen.",
    decorationCost: 0.28,
    packagingCost: 0.12,
  },
  {
    id: "cheesecake-seizoen",
    name: "Cheesecake seizoen",
    type: "finalProduct",
    productGroup: "Gebak",
    salesPrice: 6.95,
    costPrice: 1.52,
    previousCostPrice: 1.38,
    targetMargin: 80,
    currentMargin: 78,
    status: "draft",
    ingredients: [
      { ingredientId: "roomkaas", quantity: 60, unit: "gram", costContribution: 0.49 },
      { ingredientId: "frambozenpuree", quantity: 24, unit: "gram", costContribution: 0.24 },
    ],
    semiFinishedItems: [
      { semiFinishedRecipeId: "cremeux-vanille", quantity: 28, unit: "gram", costContribution: 0.26 },
      { semiFinishedRecipeId: "kersen-bitterkoekjes-vulling", quantity: 22, unit: "gram", costContribution: 0.17 },
      { semiFinishedRecipeId: "spiegelglacage", quantity: 12, unit: "gram", costContribution: 0.09 },
    ],
    preparationSteps: [
      "Cheesecake basis mengen.",
      "Seizoensvulling doseren en invriezen.",
      "Glaceren en decoreren volgens seizoen.",
    ],
    allergens: ["Melk", "Noten", "Soja"],
    version: "v0.9",
    lastUpdated: "2026-05-16",
    portionLabel: "per stuk",
    batchSize: "36 stuks",
    photoHint: "Seizoensgebak in ontwikkeling",
    notes: "Conceptrecept, marge nog valideren na proefproductie.",
    decorationCost: 0.18,
    packagingCost: 0.08,
  },
];

export const invoiceImports: InvoiceImport[] = [
  {
    id: "beko-2026-1842",
    supplier: "Beko",
    invoiceNumber: "2026-1842",
    invoiceDate: "2026-05-18",
    uploadedAt: "2026-05-18 09:42",
    status: "review",
    lines: [
      {
        articleNumber: "BE-10342",
        description: "Debic Slagroom 35% 10L",
        quantity: 4,
        unit: "can",
        totalPrice: 139.2,
        pricePerUnit: 34.8,
        matchedIngredientId: "slagroom-35",
        oldPrice: 3.2,
        newPrice: 3.48,
        percentageChange: 8.75,
        reviewStatus: "pending",
      },
      {
        articleNumber: "BE-22018",
        description: "Roomboter ongezouten 10 kg",
        quantity: 2,
        unit: "doos",
        totalPrice: 165,
        pricePerUnit: 82.5,
        matchedIngredientId: "roomboter",
        oldPrice: 7.82,
        newPrice: 8.25,
        percentageChange: 5.5,
        reviewStatus: "pending",
      },
      {
        articleNumber: "BE-99177",
        description: "Decor chocolade krullen mix",
        quantity: 1,
        unit: "doos",
        totalPrice: 27.8,
        pricePerUnit: 27.8,
        oldPrice: 0,
        newPrice: 27.8,
        percentageChange: 0,
        reviewStatus: "pending",
      },
      {
        articleNumber: "BE-66109",
        description: "Amandelpoeder fijn 5 kg",
        quantity: 1,
        unit: "zak",
        totalPrice: 64.5,
        pricePerUnit: 64.5,
        matchedIngredientId: "amandelmeel",
        oldPrice: 12.2,
        newPrice: 12.9,
        percentageChange: 5.74,
        reviewStatus: "approved",
      },
    ],
  },
];
